name: Build Windows EXE

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Windows Release
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Install Dependencies
        run: flutter pub get

      # الخطوة دي هتصلح أي نقص في ملفات الويندوز جوه السيرفر نفسه
      - name: Recreate Windows Files
        run: flutter create . --platforms windows

      - name: Build Windows App
        run: flutter build windows --release

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Payroll-App-Windows
          path: build/windows/x64/runner/Release/